name: Publish to test.pypi.org

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: pipx run poetry install --only main
    - name: Build
      run: pipx run poetry build
    - name: Set PyPI token
      run: |
        pipx run poetry config repositories.test-pypi https://test.pypi.org/legacy/
        pipx run poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_TOKEN }}
    - name: Publish
      run: pipx run poetry publish -r test-pypi
